# -*- coding: utf-8 -*-
"""Export the SHAP beeswarm of Figure 12 as plain coordinates for PGFPlots.

Input : ../../../figs/shap/shap_values.npz  (the 2,000 hold-out pixels x 11 features behind the
        published figure: arrays shap_values, X_sample, feature_names)
Output: inc_fig12_points.dat   columns  x (SHAP value)  y (row + swarm offset)  c (feature value, 0-1)
        inc_fig12_rows.tex     the y tick positions and labels, most important feature on top

The layout reproduces shap.summary_plot: features ranked by mean |SHAP|; within a row the points
are binned along x (100 bins) and stacked symmetrically about the row centre; colour is the
feature value clipped to its 5th-95th percentile range.

Run:  conda run -n geo python fig12_export_shap_points.py
"""
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
NPZ = os.path.join(HERE, '..', '..', '..', 'figs', 'shap', 'shap_values.npz')
ROW_HEIGHT = 0.4
NBINS = 100

z = np.load(NPZ, allow_pickle=True)
sv = z['shap_values']
X = z['X_sample']
names = [str(n) for n in z['feature_names']]
n = sv.shape[0]
order = np.argsort(-np.abs(sv).mean(axis=0))          # most important first
rng = np.random.RandomState(0)

rows = []
for pos, j in enumerate(order[::-1]):                  # pos 0 = bottom row
    s = sv[:, j].copy()
    v = X[:, j].astype(float).copy()
    idx = np.arange(n)
    rng.shuffle(idx)
    s, v = s[idx], v[idx]
    quant = np.round(NBINS * (s - s.min()) / (s.max() - s.min() + 1e-8))
    inds = np.argsort(quant + rng.randn(n) * 1e-6)
    layer, last = 0, -1
    ys = np.zeros(n)
    for i in inds:
        if quant[i] != last:
            layer = 0
        ys[i] = np.ceil(layer / 2.0) * ((layer % 2) * 2 - 1)
        layer += 1
        last = quant[i]
    ys *= 0.9 * (ROW_HEIGHT / np.max(ys + 1))
    lo, hi = np.nanpercentile(v, 5), np.nanpercentile(v, 95)
    if hi == lo:
        lo, hi = v.min(), v.max()
    c = np.clip((v - lo) / (hi - lo + 1e-12), 0, 1)
    for a, b, cc in zip(s, pos + ys, c):
        rows.append((a, b, cc))

rows = np.array(rows)
# draw low-|SHAP| points first so that the informative tails stay visible, as shap does per row
np.savetxt(os.path.join(HERE, 'inc_fig12_points.dat'), rows, fmt='%.4f %.4f %.3f', header='x y c', comments='')
labels = [names[j] for j in order[::-1]]
with open(os.path.join(HERE, 'inc_fig12_rows.tex'), 'w', encoding='ascii') as fh:
    fh.write('% generated by fig12_export_shap_points.py\n')
    fh.write('\\def\\ShapRowTicks{%s}\n' % ','.join(str(i) for i in range(len(labels))))
    fh.write('\\def\\ShapRowLabels{%s}\n' % ','.join(labels))
print('points:', len(rows), '| rows bottom->top:', labels)
print('x range: %.3f .. %.3f' % (rows[:, 0].min(), rows[:, 0].max()))
print('mean |SHAP| top->bottom:', ', '.join('%s %.4f' % (names[j], np.abs(sv[:, j]).mean()) for j in order))
